version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  redis:
    image: redis:latest
    ports:
      - "6380:6379"

  task:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    
      - HTTP_PORT=${HTTP_PORT}

      - JWT_ACCESS_TOKEN_SECRET_KEY=${JWT_ACCESS_TOKEN_SECRET_KEY}
    
      - SIGNUP_AUTHENTICATION_DURATION=${SIGNUP_AUTHENTICATION_DURATION}
      - ACCESS_TOKEN_DURATION=${ACCESS_TOKEN_DURATION}
    
      - SMTP_SENDER=${SMTP_SENDER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
       
      - REDIS_ADDR=${REDIS_ADDR}
      
      - AUTHORIZATION_HEADER_KEY=${AUTHORIZATION_HEADER_KEY}
      - AUTHORIZATION_PAYLOAD_KEY=${AUTHORIZATION_PAYLOAD_KEY}
    depends_on:
      - postgres
      - redis
    restart: always

volumes:
  postgres_data: