name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REP }}

      - name: Get the image digest
        run: echo "Docker image digest ${{ steps.docker_build.outputs.digest }}"

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Install Migrate
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz
          tar -xvf migrate.linux-amd64.tar.gz
          mv migrate.linux-amd64 migrate
          chmod +x migrate
      
      - name: SSH into the server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP_ADDRESS }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd test-task-dels
            make up
            migrate -path ./migrations -database "${{ secrets.DATABASE_URL }}" -verbose up